### ISSUE TITLE
What makes the glider being drifted? (same question asked on notion)

### ISSUE THREAD

**Issue by woensug-choi** [KMOU-IOES/dave#9]
@rakeshv24 Which part of the code make the glider being drifted? It could be helpful for @GauravKumar9920 on migration of ocean current plugin. The ocean wave model being used in the world sdf was only for visual unless https://github.com/srmainwaring/asv_wave_sim is ported.

**Comment by rakeshv24** [comment]
@woensug-choi my immediate response is that the buoyancy plugin is causing the vehicle to move. However, when I adjust the vehicle's mass to make it neutrally buoyant as mentioned [here](https://gazebosim.org/api/sim/8/theory_buoyancy.html), the drift doesn't appear as much. Additionally, we might need to use a better set of added mass values.

**Comment by woensug-choi** [comment]
Conversation continues at https://yeongdocat.notion.site/Under-water-Current-Dave-9905dc2a4ad54b6da0fceea023f7cf04?pvs=4
